FROM fluent/fluent-bit:1.6
COPY fluent-bit.conf /fluent-bit/etc/fluent-bit.conf
COPY parsers.conf /fluent-bit/etc/parsers.conf
ENTRYPOINT ["/fluent-bit/bin/fluent-bit", "-c","/fluent-bit/etc/fluent-bit.conf"]