FROM python:3.8
WORKDIR /app
COPY log.py log.py
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip -r requirements.txt
ENTRYPOINT ["sh", "-c","python log.py --logdir $LOGDIR --size $SIZE --backups $BACKUPS --interval $INTERVAL"]